name: 🔄 Update galaxy token

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.REPO_CTRL_TOKEN }}
  ANSIBLE_GALAXY_TOKEN: ${{ secrets.GALAXY_TOKEN }}
  ROLE_REPO_LIST: ${{ vars.ROLE_REPO_LIST }}

jobs:
  prepare-repo-list:
    runs-on: ubuntu-latest
    outputs:
      repo_list: ${{ steps.prepare.outputs.repo_list }}
    steps:
      - name: 💱 Convert comma-separated list to JSON array
        id: prepare
        run: |
          # Convert ROLE_REPO_LIST from comma-separated to JSON array
          repos="[\"$(echo '${{ env.ROLE_REPO_LIST }}' | tr -d '[:space:]' | sed 's/,\s*$//' | sed 's/,/\",\"/g')\"]"
          echo "repo_list=$repos" >> $GITHUB_OUTPUT

      - name: Log repo list
        run: |
          echo "Converted repo list: ${{ steps.prepare.outputs.repo_list }}"

  update-galaxy-token:
    runs-on: ubuntu-latest
    needs: prepare-repo-list

    strategy:
      matrix:
        repo: ${{ fromJson(needs.prepare-repo-list.outputs.repo_list) }}

    steps:
      - name: 💾 Set or update galaxy token
        run: |
          gh secret set ANSIBLE_GALAXY_TOKEN --body "${{ env.ANSIBLE_GALAXY_TOKEN }}" --repo "${{ github.repository_owner }}/${{ matrix.repo }}"
